---
- name: Copie du fichier de configuration nécessaire
  template:
    src: "audit.rules.j2"
    dest: "/etc/audit/rules.d/audit.rules"
    owner: root
    group: root
    mode: '0644'
  notify: Redémarrage d'Auditd
...
