---
- name: Création des utilisateurs
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    append: "{{ 'yes' if item.groups is defined else 'no' }}"
    shell: "{{ item.shell | default(omit) }}"
    state: "{{ item.state }}"
    force: yes
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
...
